# Rich Airport Data with Timezone and Coordinates
# Source: Approximate coordinates and standard timezones

AIRPORTS_LIST = [
    {"code": "ABQ", "name": "Albuquerque International Sunport", "city": "Albuquerque", "timezone": "America/Denver", "lat": 35.0402, "lon": -106.6091},
    {"code": "ALB", "name": "Albany International Airport", "city": "Albany", "timezone": "America/New_York", "lat": 42.7481, "lon": -73.8029},
    {"code": "ANC", "name": "Ted Stevens Anchorage International Airport", "city": "Anchorage", "timezone": "America/Anchorage", "lat": 61.1743, "lon": -149.9961},
    {"code": "ANU", "name": "V. C. Bird International Airport", "city": "Antigua", "timezone": "America/Antigua", "lat": 17.1367, "lon": -61.7927, "is_international": True},
    {"code": "ATL", "name": "Hartsfield-Jackson Atlanta International Airport", "city": "Atlanta", "timezone": "America/New_York", "lat": 33.6407, "lon": -84.4277},
    {"code": "ATW", "name": "Appleton International Airport", "city": "Appleton", "timezone": "America/Chicago", "lat": 44.2574, "lon": -88.5194},
    {"code": "AUS", "name": "Austin-Bergstrom International Airport", "city": "Austin", "timezone": "America/Chicago", "lat": 30.1974, "lon": -97.6663},
    {"code": "AZA", "name": "Phoenix-Mesa Gateway Airport", "city": "Phoenix", "timezone": "America/Phoenix", "lat": 33.3078, "lon": -111.6550},
    {"code": "BDL", "name": "Bradley International Airport", "city": "Hartford", "timezone": "America/New_York", "lat": 41.9388, "lon": -72.6832},
    {"code": "BFL", "name": "Meadows Field", "city": "Bakersfield", "timezone": "America/Los_Angeles", "lat": 35.4335, "lon": -119.0567},
    {"code": "BFM", "name": "Mobile Downtown Airport", "city": "Mobile", "timezone": "America/Chicago", "lat": 30.6265, "lon": -88.0681},
    {"code": "BGI", "name": "Grantley Adams International Airport", "city": "Barbados", "timezone": "America/Barbados", "lat": 13.0746, "lon": -59.4924, "is_international": True},
    {"code": "BHM", "name": "Birmingham-Shuttlesworth International Airport", "city": "Birmingham", "timezone": "America/Chicago", "lat": 33.5629, "lon": -86.7535},
    {"code": "BIL", "name": "Billings Logan International Airport", "city": "Billings", "timezone": "America/Denver", "lat": 45.8076, "lon": -108.5428},
    {"code": "BIS", "name": "Bismarck Municipal Airport", "city": "Bismarck", "timezone": "America/Chicago", "lat": 46.7741, "lon": -100.7467},
    {"code": "BKG", "name": "Branson Airport", "city": "Branson", "timezone": "America/Chicago", "lat": 36.5319, "lon": -93.2005},
    {"code": "BLI", "name": "Bellingham International Airport", "city": "Bellingham", "timezone": "America/Los_Angeles", "lat": 48.7927, "lon": -122.5375},
    {"code": "BMI", "name": "Central Illinois Regional Airport", "city": "Bloomington", "timezone": "America/Chicago", "lat": 40.4771, "lon": -88.9159},
    {"code": "BNA", "name": "Nashville International Airport", "city": "Nashville", "timezone": "America/Chicago", "lat": 36.1244, "lon": -86.6781},
    {"code": "BOI", "name": "Boise Airport", "city": "Boise", "timezone": "America/Boise", "lat": 43.5644, "lon": -116.2227},
    {"code": "BOS", "name": "Logan International Airport", "city": "Boston", "timezone": "America/New_York", "lat": 42.3656, "lon": -71.0095},
    {"code": "BQN", "name": "Rafael Hernández Airport", "city": "Aguadilla", "timezone": "America/Puerto_Rico", "lat": 18.4948, "lon": -67.1294},
    {"code": "BTV", "name": "Burlington International Airport", "city": "Burlington", "timezone": "America/New_York", "lat": 44.4730, "lon": -73.1503},
    {"code": "BUF", "name": "Buffalo Niagara International Airport", "city": "Buffalo", "timezone": "America/New_York", "lat": 42.9405, "lon": -78.7321},
    {"code": "BUR", "name": "Hollywood Burbank Airport", "city": "Burbank", "timezone": "America/Los_Angeles", "lat": 34.2006, "lon": -118.3586},
    {"code": "BWI", "name": "Baltimore/Washington International Thurgood Marshall Airport", "city": "Baltimore", "timezone": "America/New_York", "lat": 39.1754, "lon": -76.6681},
    {"code": "BZE", "name": "Philip S. W. Goldson International Airport", "city": "Belize City", "timezone": "America/Belize", "lat": 17.5391, "lon": -88.3082, "is_international": True},
    {"code": "CID", "name": "The Eastern Iowa Airport", "city": "Cedar Rapids", "timezone": "America/Chicago", "lat": 41.8846, "lon": -91.7108},
    {"code": "CLE", "name": "Cleveland Hopkins International Airport", "city": "Cleveland", "timezone": "America/New_York", "lat": 41.4108, "lon": -81.8493},
    {"code": "CLT", "name": "Charlotte Douglas International Airport", "city": "Charlotte", "timezone": "America/New_York", "lat": 35.2140, "lon": -80.9431},
    {"code": "CMH", "name": "John Glenn Columbus International Airport", "city": "Columbus", "timezone": "America/New_York", "lat": 39.9979, "lon": -82.8918},
    {"code": "COS", "name": "City of Colorado Springs Municipal Airport", "city": "Colorado Springs", "timezone": "America/Denver", "lat": 38.8058, "lon": -104.7007},
    {"code": "COU", "name": "Columbia Regional Airport", "city": "Columbia", "timezone": "America/Chicago", "lat": 38.8180, "lon": -92.2196},
    {"code": "CRP", "name": "Corpus Christi International Airport", "city": "Corpus Christi", "timezone": "America/Chicago", "lat": 27.7703, "lon": -97.5012},
    {"code": "CUN", "name": "Cancún International Airport", "city": "Cancun", "timezone": "America/Cancun", "lat": 21.0366, "lon": -86.8770, "is_international": True},
    {"code": "CVG", "name": "Cincinnati/Northern Kentucky International Airport", "city": "Cincinnati", "timezone": "America/New_York", "lat": 39.0461, "lon": -84.6621},
    {"code": "CZM", "name": "Cozumel International Airport", "city": "Cozumel", "timezone": "America/Cancun", "lat": 20.5224, "lon": -86.9255, "is_international": True},
    {"code": "DCA", "name": "Ronald Reagan Washington National Airport", "city": "Washington D.C.", "timezone": "America/New_York", "lat": 38.8512, "lon": -77.0402},
    {"code": "DEN", "name": "Denver International Airport", "city": "Denver", "timezone": "America/Denver", "lat": 39.8560, "lon": -104.6737},
    {"code": "DFW", "name": "Dallas/Fort Worth International Airport", "city": "Dallas", "timezone": "America/Chicago", "lat": 32.8998, "lon": -97.0403},
    {"code": "DSM", "name": "Des Moines International Airport", "city": "Des Moines", "timezone": "America/Chicago", "lat": 41.5349, "lon": -93.6630},
    {"code": "DTW", "name": "Detroit Metropolitan Wayne County Airport", "city": "Detroit", "timezone": "America/Detroit", "lat": 42.2120, "lon": -83.3533},
    {"code": "ELP", "name": "El Paso International Airport", "city": "El Paso", "timezone": "America/Denver", "lat": 31.8072, "lon": -106.3775},
    {"code": "EWR", "name": "Newark Liberty International Airport", "city": "Newark", "timezone": "America/New_York", "lat": 40.6895, "lon": -74.1744},
    {"code": "FAR", "name": "Hector International Airport", "city": "Fargo", "timezone": "America/Chicago", "lat": 46.9193, "lon": -96.8111},
    {"code": "FAT", "name": "Fresno Yosemite International Airport", "city": "Fresno", "timezone": "America/Los_Angeles", "lat": 36.7761, "lon": -119.7181},
    {"code": "FLL", "name": "Fort Lauderdale–Hollywood International Airport", "city": "Fort Lauderdale", "timezone": "America/New_York", "lat": 26.0742, "lon": -80.1506},
    {"code": "FSD", "name": "Sioux Falls Regional Airport", "city": "Sioux Falls", "timezone": "America/Chicago", "lat": 43.5813, "lon": -96.7417},
    {"code": "GEG", "name": "Spokane International Airport", "city": "Spokane", "timezone": "America/Los_Angeles", "lat": 47.6190, "lon": -117.5352},
    {"code": "GFK", "name": "Grand Forks International Airport", "city": "Grand Forks", "timezone": "America/Chicago", "lat": 47.9492, "lon": -97.1761},
    {"code": "GJT", "name": "Grand Junction Regional Airport", "city": "Grand Junction", "timezone": "America/Denver", "lat": 39.1224, "lon": -108.5267},
    {"code": "GRB", "name": "Green Bay–Austin Straubel International Airport", "city": "Green Bay", "timezone": "America/Chicago", "lat": 44.4850, "lon": -88.1295},
    {"code": "GRR", "name": "Gerald R. Ford International Airport", "city": "Grand Rapids", "timezone": "America/Detroit", "lat": 42.8808, "lon": -85.5227},
    {"code": "GSO", "name": "Piedmont Triad International Airport", "city": "Greensboro", "timezone": "America/New_York", "lat": 36.0977, "lon": -79.9372},
    {"code": "GSP", "name": "Greenville-Spartanburg International Airport", "city": "Greenville", "timezone": "America/New_York", "lat": 34.8960, "lon": -82.2188},
    {"code": "GUA", "name": "La Aurora International Airport", "city": "Guatemala City", "timezone": "America/Guatemala", "lat": 14.5832, "lon": -90.5274, "is_international": True},
    {"code": "HOU", "name": "William P. Hobby Airport", "city": "Houston", "timezone": "America/Chicago", "lat": 29.6454, "lon": -95.2788},
    {"code": "IAD", "name": "Washington Dulles International Airport", "city": "Washington D.C.", "timezone": "America/New_York", "lat": 38.9531, "lon": -77.4565},
    {"code": "IAH", "name": "George Bush Intercontinental Airport", "city": "Houston", "timezone": "America/Chicago", "lat": 29.9902, "lon": -95.3367},
    {"code": "ICT", "name": "Wichita Dwight D. Eisenhower National Airport", "city": "Wichita", "timezone": "America/Chicago", "lat": 37.6499, "lon": -97.4330},
    {"code": "IND", "name": "Indianapolis International Airport", "city": "Indianapolis", "timezone": "America/Indiana/Indianapolis", "lat": 39.7173, "lon": -86.2943},
    {"code": "ISP", "name": "Long Island MacArthur Airport", "city": "Islip", "timezone": "America/New_York", "lat": 40.7952, "lon": -73.1002},
    {"code": "JAN", "name": "Jackson-Medgar Wiley Evers International Airport", "city": "Jackson (MS)", "timezone": "America/Chicago", "lat": 32.3111, "lon": -90.0758},
    {"code": "JAX", "name": "Jacksonville International Airport", "city": "Jacksonville", "timezone": "America/New_York", "lat": 30.4940, "lon": -81.6878},
    {"code": "JFK", "name": "John F. Kennedy International Airport", "city": "New York City", "timezone": "America/New_York", "lat": 40.6413, "lon": -73.7781},
    {"code": "LAS", "name": "Harry Reid International Airport", "city": "Las Vegas", "timezone": "America/Los_Angeles", "lat": 36.0840, "lon": -115.1537},
    {"code": "LAX", "name": "Los Angeles International Airport", "city": "Los Angeles", "timezone": "America/Los_Angeles", "lat": 33.9415, "lon": -118.4085},
    {"code": "LGA", "name": "LaGuardia Airport", "city": "New York City", "timezone": "America/New_York", "lat": 40.7769, "lon": -73.8739},
    {"code": "LIR", "name": "Daniel Oduber Quirós International Airport", "city": "Liberia", "timezone": "America/Costa_Rica", "lat": 10.6010, "lon": -85.5449, "is_international": True},
    {"code": "LIT", "name": "Bill and Hillary Clinton National Airport", "city": "Little Rock", "timezone": "America/Chicago", "lat": 34.7293, "lon": -92.2242},
    {"code": "MBJ", "name": "Sangster International Airport", "city": "Montego Bay", "timezone": "America/Jamaica", "lat": 18.5037, "lon": -77.9133, "is_international": True},
    {"code": "MCI", "name": "Kansas City International Airport", "city": "Kansas City", "timezone": "America/Chicago", "lat": 39.2976, "lon": -94.7139},
    {"code": "MCO", "name": "Orlando International Airport", "city": "Orlando", "timezone": "America/New_York", "lat": 28.4311, "lon": -81.3080},
    {"code": "MDT", "name": "Harrisburg International Airport", "city": "Harrisburg", "timezone": "America/New_York", "lat": 40.1935, "lon": -76.7634},
    {"code": "MDW", "name": "Midway International Airport", "city": "Chicago", "timezone": "America/Chicago", "lat": 41.7867, "lon": -87.7521},
    {"code": "MEM", "name": "Memphis International Airport", "city": "Memphis", "timezone": "America/Chicago", "lat": 35.0420, "lon": -89.9791},
    {"code": "MIA", "name": "Miami International Airport", "city": "Miami", "timezone": "America/New_York", "lat": 25.7958, "lon": -80.2870},
    {"code": "MKE", "name": "Milwaukee Mitchell International Airport", "city": "Milwaukee", "timezone": "America/Chicago", "lat": 42.9475, "lon": -87.8965},
    {"code": "MSP", "name": "Minneapolis–Saint Paul International Airport", "city": "Minneapolis", "timezone": "America/Chicago", "lat": 44.8847, "lon": -93.2222},
    {"code": "MSY", "name": "Louis Armstrong New Orleans International Airport", "city": "New Orleans", "timezone": "America/Chicago", "lat": 29.9910, "lon": -90.2592},
    {"code": "MYR", "name": "Myrtle Beach International Airport", "city": "Myrtle Beach", "timezone": "America/New_York", "lat": 33.6820, "lon": -78.9283},
    {"code": "OAK", "name": "Oakland International Airport", "city": "Oakland", "timezone": "America/Los_Angeles", "lat": 37.7212, "lon": -122.2207},
    {"code": "OKC", "name": "Will Rogers World Airport", "city": "Oklahoma City", "timezone": "America/Chicago", "lat": 35.3930, "lon": -97.6007},
    {"code": "OMA", "name": "Eppley Airfield", "city": "Omaha", "timezone": "America/Chicago", "lat": 41.3025, "lon": -95.8941},
    {"code": "ONT", "name": "Ontario International Airport", "city": "Ontario", "timezone": "America/Los_Angeles", "lat": 34.0560, "lon": -117.6011},
    {"code": "ORD", "name": "O'Hare International Airport", "city": "Chicago", "timezone": "America/Chicago", "lat": 41.9741, "lon": -87.9073},
    {"code": "ORF", "name": "Norfolk International Airport", "city": "Norfolk", "timezone": "America/New_York", "lat": 36.8946, "lon": -76.2012},
    {"code": "PBI", "name": "Palm Beach International Airport", "city": "West Palm Beach", "timezone": "America/New_York", "lat": 26.6831, "lon": -80.0955},
    {"code": "PDX", "name": "Portland International Airport", "city": "Portland (OR)", "timezone": "America/Los_Angeles", "lat": 45.5897, "lon": -122.5950},
    {"code": "PHL", "name": "Philadelphia International Airport", "city": "Philadelphia", "timezone": "America/New_York", "lat": 39.8720, "lon": -75.2406},
    {"code": "PHX", "name": "Phoenix Sky Harbor International Airport", "city": "Phoenix", "timezone": "America/Phoenix", "lat": 33.4341, "lon": -112.0080},
    {"code": "PIT", "name": "Pittsburgh International Airport", "city": "Pittsburgh", "timezone": "America/New_York", "lat": 40.4914, "lon": -80.2328},
    {"code": "PNS", "name": "Pensacola International Airport", "city": "Pensacola", "timezone": "America/Chicago", "lat": 30.4733, "lon": -87.1874},
    {"code": "POP", "name": "Gregorio Luperón International Airport", "city": "Puerto Plata", "timezone": "America/Santo_Domingo", "lat": 19.7579, "lon": -70.5699, "is_international": True},
    {"code": "POS", "name": "Piarco International Airport", "city": "Port of Spain", "timezone": "America/Port_of_Spain", "lat": 10.5953, "lon": -61.3372, "is_international": True},
    {"code": "PSP", "name": "Palm Springs International Airport", "city": "Palm Springs", "timezone": "America/Los_Angeles", "lat": 33.8296, "lon": -116.5066},
    {"code": "PUJ", "name": "Punta Cana International Airport", "city": "Punta Cana", "timezone": "America/Santo_Domingo", "lat": 18.5673, "lon": -68.3634, "is_international": True},
    {"code": "PVD", "name": "Rhode Island T. F. Green International Airport", "city": "Providence", "timezone": "America/New_York", "lat": 41.7239, "lon": -71.4282},
    {"code": "PWM", "name": "Portland International Jetport", "city": "Portland (ME)", "timezone": "America/New_York", "lat": 43.6461, "lon": -70.3086},
    {"code": "RDU", "name": "Raleigh-Durham International Airport", "city": "Raleigh", "timezone": "America/New_York", "lat": 35.8800, "lon": -78.7879},
    {"code": "RIC", "name": "Richmond International Airport", "city": "Richmond", "timezone": "America/New_York", "lat": 37.5051, "lon": -77.3196},
    {"code": "RNO", "name": "Reno-Tahoe International Airport", "city": "Reno", "timezone": "America/Los_Angeles", "lat": 39.4991, "lon": -119.7681},
    {"code": "RSW", "name": "Southwest Florida International Airport", "city": "Fort Myers", "timezone": "America/New_York", "lat": 26.5361, "lon": -81.7551},
    {"code": "SAL", "name": "El Salvador International Airport", "city": "San Salvador", "timezone": "America/El_Salvador", "lat": 13.4409, "lon": -89.0557, "is_international": True},
    {"code": "SAN", "name": "San Diego International Airport", "city": "San Diego", "timezone": "America/Los_Angeles", "lat": 32.7338, "lon": -117.1933},
    {"code": "SAT", "name": "San Antonio International Airport", "city": "San Antonio", "timezone": "America/Chicago", "lat": 29.5336, "lon": -98.4697},
    {"code": "SAV", "name": "Savannah/Hilton Head International Airport", "city": "Savannah", "timezone": "America/New_York", "lat": 32.1275, "lon": -81.2021},
    {"code": "SBN", "name": "South Bend International Airport", "city": "South Bend", "timezone": "America/Indiana/Indianapolis", "lat": 41.7087, "lon": -86.3173},
    {"code": "SDF", "name": "Louisville Muhammad Ali International Airport", "city": "Louisville", "timezone": "America/Kentucky/Louisville", "lat": 38.1743, "lon": -85.7360},
    {"code": "SDQ", "name": "Las Américas International Airport", "city": "Santo Domingo", "timezone": "America/Santo_Domingo", "lat": 18.4296, "lon": -69.6689, "is_international": True},
    {"code": "SEA", "name": "Seattle-Tacoma International Airport", "city": "Seattle", "timezone": "America/Los_Angeles", "lat": 47.4502, "lon": -122.3088},
    {"code": "SFO", "name": "San Francisco International Airport", "city": "San Francisco", "timezone": "America/Los_Angeles", "lat": 37.6189, "lon": -122.3748},
    {"code": "SJC", "name": "Norman Y. Mineta San Jose International Airport", "city": "San Jose (CA)", "timezone": "America/Los_Angeles", "lat": 37.3618, "lon": -121.9290},
    {"code": "SJD", "name": "Los Cabos International Airport", "city": "Cabo San Lucas", "timezone": "America/Mazatlan", "lat": 23.1518, "lon": -109.7210, "is_international": True},
    {"code": "SJO", "name": "Juan Santamaría International Airport", "city": "San Jose (Costa Rica)", "timezone": "America/Costa_Rica", "lat": 9.9938, "lon": -84.2088, "is_international": True},
    {"code": "SJU", "name": "Luis Muñoz Marín International Airport", "city": "San Juan", "timezone": "America/Puerto_Rico", "lat": 18.4394, "lon": -66.0018},
    {"code": "SLC", "name": "Salt Lake City International Airport", "city": "Salt Lake City", "timezone": "America/Denver", "lat": 40.7899, "lon": -111.9790},
    {"code": "SMF", "name": "Sacramento International Airport", "city": "Sacramento", "timezone": "America/Los_Angeles", "lat": 38.6954, "lon": -121.5907},
    {"code": "SNA", "name": "John Wayne Airport", "city": "Santa Ana", "timezone": "America/Los_Angeles", "lat": 33.6761, "lon": -117.8674},
    {"code": "SRQ", "name": "Sarasota-Bradenton International Airport", "city": "Sarasota", "timezone": "America/New_York", "lat": 27.3954, "lon": -82.5544},
    {"code": "STI", "name": "Cibao International Airport", "city": "Santiago de los Caballeros", "timezone": "America/Santo_Domingo", "lat": 19.4069, "lon": -70.6047, "is_international": True},
    {"code": "STL", "name": "St. Louis Lambert International Airport", "city": "St. Louis", "timezone": "America/Chicago", "lat": 38.7472, "lon": -90.3614},
    {"code": "STT", "name": "Cyril E. King Airport", "city": "St. Thomas", "timezone": "America/St_Thomas", "lat": 18.3372, "lon": -64.9722},
    {"code": "STX", "name": "Henry E. Rohlsen Airport", "city": "St. Croix", "timezone": "America/St_Thomas", "lat": 17.7018, "lon": -64.7985},
    {"code": "SWF", "name": "New York Stewart International Airport", "city": "New York City", "timezone": "America/New_York", "lat": 41.5040, "lon": -74.1048},
    {"code": "SYR", "name": "Syracuse Hancock International Airport", "city": "Syracuse", "timezone": "America/New_York", "lat": 43.1111, "lon": -76.1063},
    {"code": "TPA", "name": "Tampa International Airport", "city": "Tampa", "timezone": "America/New_York", "lat": 27.9772, "lon": -82.5311},
    {"code": "TTN", "name": "Trenton-Mercer Airport", "city": "Trenton", "timezone": "America/New_York", "lat": 40.2766, "lon": -74.8134},
    {"code": "TUL", "name": "Tulsa International Airport", "city": "Tulsa", "timezone": "America/Chicago", "lat": 36.1983, "lon": -95.8882},
    {"code": "TYS", "name": "McGhee Tyson Airport", "city": "Knoxville", "timezone": "America/New_York", "lat": 35.8124, "lon": -83.9928},
    {"code": "YVR", "name": "Vancouver International Airport", "city": "Vancouver", "timezone": "America/Vancouver", "lat": 49.1947, "lon": -123.1791, "is_international": True},
    {"code": "YYC", "name": "Calgary International Airport", "city": "Calgary", "timezone": "America/Edmonton", "lat": 51.1313, "lon": -114.0112, "is_international": True}
]

# Simple mapping for legacy compatibility
AIRPORT_MAPPING = {}
for entry in AIRPORTS_LIST:
    city = entry["city"]
    code = entry["code"]
    if city not in AIRPORT_MAPPING:
        AIRPORT_MAPPING[city] = []
    AIRPORT_MAPPING[city].append(code)

# Helper to get city code (grouping airports)
def get_city_code(airport_code):
    for entry in AIRPORTS_LIST:
        if entry["code"] == airport_code:
            return entry["city"]
    return None